<a href="https://colab.research.google.com/github/Sriveni-bonam/Pandas_for_DataEngineering/blob/main/Pandas_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
data = {
    "name": ["Sumit", "Rahul", "Ankit"],
    "age": [25, 30, 35],
    "salary": [25000, 30000, 35000],
}
df1=pd.DataFrame(data)
print(df1)

    name  age  salary
0  Sumit   25   25000
1  Rahul   30   30000
2  Ankit   35   35000

Read from csv file

In [ ]:
orders=pd.read_csv('orders.csv')
print(orders)

          order_id  order_date   ship_date       ship_mode customer_id  \
0   CA-2020-152156  08-11-2020  11-11-2020    Second Class    CG-12520
1   CA-2020-152156  08-11-2020  11-11-2020    Second Class    CG-12520
2   CA-2020-138688  12-06-2020  16-06-2020  Standard Class    DV-13045
3   US-2019-108966  11-10-2019  18-10-2019  Standard Class    SO-20335
4   US-2019-108966  11-10-2019  18-10-2019  Standard Class    SO-20335
5   CA-2018-115812  09-06-2018  14-06-2018  Standard Class    BH-11710
6   CA-2018-115812  09-06-2018  14-06-2018  Standard Class    BH-11710
7   CA-2018-115812  09-06-2018  14-06-2018  Standard Class    BH-11710
8   CA-2018-115812  09-06-2018  14-06-2018  Standard Class    BH-11710
9   CA-2018-115812  09-06-2018  14-06-2018  Standard Class    BH-11710
10  CA-2018-115812  09-06-2018  14-06-2018  Standard Class    BH-11710
11  CA-2018-115812  09-06-2018  14-06-2018  Standard Class    BH-11710
12  CA-2021-114412  15-04-2021  20-04-2021  Standard Class    AA-10480
13  CA-2020-161389  05-12-2020  10-12-2020  Standard Class    IM-15070
14  US-2019-118983  22-11-2019  26-11-2019  Standard Class    HP-14815
15  US-2019-118983  22-11-2019  26-11-2019  Standard Class    HP-14815
16  CA-2018-105893  11-11-2018  18-11-2018  Standard Class    PK-19075
17  CA-2018-167164  13-05-2018  15-05-2018    Second Class    AG-10270
18  CA-2018-143336  27-08-2018  01-09-2018    Second Class    ZD-21925
19  CA-2018-143336  27-08-2018  01-09-2018    Second Class    ZD-21925
20  CA-2018-143336  27-08-2018  01-09-2018    Second Class    ZD-21925
21  CA-2020-137330  09-12-2020  13-12-2020  Standard Class    KB-16585
22  CA-2020-137330  09-12-2020  13-12-2020  Standard Class    KB-16585
23  US-2021-156909  16-07-2021  18-07-2021    Second Class    SF-20065
24  CA-2019-106320  25-09-2019  30-09-2019  Standard Class    EB-13870
25  CA-2020-121755  16-01-2020  20-01-2020    Second Class    EH-13945
26  CA-2020-121755  16-01-2020  20-01-2020    Second Class    EH-13945
27  US-2019-150630  17-09-2019  21-09-2019  Standard Class    TB-21520
28  US-2019-150630  17-09-2019  21-09-2019  Standard Class    TB-21520
29  US-2019-150630  17-09-2019  21-09-2019  Standard Class    TB-21520
30  US-2019-150630  17-09-2019  21-09-2019  Standard Class    TB-21520
31  US-2019-150630  17-09-2019  21-09-2019  Standard Class    TB-21520
32  US-2019-150630  17-09-2019  21-09-2019  Standard Class    TB-21520
33  US-2019-150630  17-09-2019  21-09-2019  Standard Class    TB-21520
34  CA-2021-107727  19-10-2021  23-10-2021    Second Class    MA-17560
35  CA-2020-117590  08-12-2020  10-12-2020     First Class    GH-14485
36  CA-2020-117590  08-12-2020  10-12-2020     First Class    GH-14485
37  CA-2019-117415  27-12-2019  31-12-2019  Standard Class    SN-20710
38  CA-2019-117415  27-12-2019  31-12-2019  Standard Class    SN-20710
39  CA-2019-117415  27-12-2019  31-12-2019  Standard Class    SN-20710
40  CA-2019-117415  27-12-2019  31-12-2019  Standard Class    SN-20710
41  CA-2021-120999  10-09-2021  15-09-2021  Standard Class    LC-16930
42  CA-2020-101343  17-07-2020  22-07-2020  Standard Class    RA-19885
43  CA-2021-139619  19-09-2021  23-09-2021  Standard Class    ES-14080
44  CA-2020-118255  11-03-2020  13-03-2020     First Class    ON-18715
45  CA-2020-118255  11-03-2020  13-03-2020     First Class    ON-18715
46  CA-2018-146703  20-10-2018  25-10-2018    Second Class    PO-18865
47  CA-2020-169194  20-06-2020  25-06-2020  Standard Class    LH-16900
48  CA-2020-169194  20-06-2020  25-06-2020  Standard Class    LH-16900
49  CA-2019-115742  18-04-2019  22-04-2019  Standard Class    DP-13000

     region       product_id         category   sales  quantity  profit
0     South  FUR-BO-10001798  Office Supplies   262.0         2    41.9
1     South  FUR-CH-10000454        Furniture   731.9         3   219.6
2      West  OFF-LA-10000240  Office Supplies    14.6         2     6.9
3     South  FUR-TA-10000577        Furniture   957.6         5  -383.0
4     South  OFF-ST-10000760  Office Supplies    22.4         2     2.5
5      West  FUR-FU-10001487        Furniture    48.9         7    14.2
6      West  OFF-AR-10002833  Office Supplies     7.3         4     2.0
7      West  TEC-PH-10002275       Technology   907.2         6    90.7
8      West  OFF-BI-10003910  Office Supplies    18.5         3     5.8
9      West  OFF-AP-10002892  Office Supplies   114.9         5    34.5
10     West  FUR-TA-10001539        Furniture  1706.2         9    85.3
11     West  TEC-PH-10002033       Technology   911.4         4    68.4
12    South  OFF-PA-10002365  Office Supplies    15.6         3     5.4
13     West  OFF-BI-10003656  Office Supplies   408.0         3   132.6
14  Central  OFF-AP-10002311  Office Supplies    68.8         5  -123.9
15  Central  OFF-BI-10000756  Office Supplies     2.5         3    -3.8
16  Central  OFF-ST-10004186  Office Supplies   665.9         6    13.3
17     West  OFF-ST-10000107  Office Supplies    55.5         2    10.0
18     West  OFF-AR-10003056  Office Supplies     8.6         2     2.5
19     West  TEC-PH-10001949       Technology   213.5         3    16.0
20     West  OFF-BI-10002215  Office Supplies    22.7         4     7.4
21  Central  OFF-AR-10000246  Office Supplies    19.5         7     5.1
22  Central  OFF-AP-10001492  Office Supplies    60.3         7    15.7
23     East  FUR-CH-10002774        Furniture    71.4         2    -1.0
24     West  FUR-TA-10000577        Furniture  1044.6         3   240.3
25     West  OFF-BI-10001634  Office Supplies    11.6         2     4.2
26     West  TEC-AC-10003027       Technology    90.6         3    11.8
27     East  FUR-BO-10004834        Furniture  3083.4         7 -1665.1
28     East  OFF-BI-10000474  Office Supplies     9.6         2    -7.1
29     East  FUR-FU-10004848        Furniture   124.2         3    15.5
30     East  OFF-EN-10001509  Office Supplies     3.3         2     1.1
31     East  OFF-AR-10004042  Office Supplies    86.3         6     9.7
32     East  OFF-BI-10001525  Office Supplies     6.9         6    -5.7
33     East  OFF-AR-10001683  Office Supplies    15.8         2     3.5
34  Central  OFF-PA-10000249  Office Supplies    29.5         3     9.9
35  Central  TEC-PH-10004977       Technology  1097.5         7   123.5
36  Central  FUR-FU-10003664        Furniture   190.9         5  -148.0
37  Central  OFF-EN-10002986  Office Supplies   113.3         9    35.4
38  Central  FUR-BO-10002545        Furniture   532.4         3   -47.0
39  Central  FUR-CH-10004218        Furniture   212.1         3   -15.1
40  Central  TEC-PH-10000486       Technology   371.2         4    41.8
41  Central  TEC-PH-10004093       Technology   147.2         4    16.6
42     West  OFF-ST-10003479  Office Supplies    77.9         2     3.9
43    South  OFF-ST-10003282  Office Supplies    95.6         2     9.6
44  Central  TEC-AC-10000171       Technology    46.0         2    19.8
45  Central  OFF-BI-10003291  Office Supplies    17.5         2     8.2
46  Central  OFF-ST-10001713  Office Supplies   212.0         4     8.5
47     East  TEC-AC-10002167       Technology    45.0         3     5.0
48     East  TEC-PH-10003988       Technology    21.8         2     6.1
49  Central  OFF-BI-10004410  Office Supplies    38.2         6    18.0

head() - returns first 5 rows

In [ ]:
print(orders.head())

         order_id  order_date   ship_date       ship_mode customer_id region  \
0  CA-2020-152156  08-11-2020  11-11-2020    Second Class    CG-12520  South
1  CA-2020-152156  08-11-2020  11-11-2020    Second Class    CG-12520  South
2  CA-2020-138688  12-06-2020  16-06-2020  Standard Class    DV-13045   West
3  US-2019-108966  11-10-2019  18-10-2019  Standard Class    SO-20335  South
4  US-2019-108966  11-10-2019  18-10-2019  Standard Class    SO-20335  South

        product_id         category  sales  quantity  profit
0  FUR-BO-10001798  Office Supplies  262.0         2    41.9
1  FUR-CH-10000454        Furniture  731.9         3   219.6
2  OFF-LA-10000240  Office Supplies   14.6         2     6.9
3  FUR-TA-10000577        Furniture  957.6         5  -383.0
4  OFF-ST-10000760  Office Supplies   22.4         2     2.5

tail() - returns last 5 rows

In [ ]:
print(orders.tail())

          order_id  order_date   ship_date       ship_mode customer_id  \
45  CA-2020-118255  11-03-2020  13-03-2020     First Class    ON-18715
46  CA-2018-146703  20-10-2018  25-10-2018    Second Class    PO-18865
47  CA-2020-169194  20-06-2020  25-06-2020  Standard Class    LH-16900
48  CA-2020-169194  20-06-2020  25-06-2020  Standard Class    LH-16900
49  CA-2019-115742  18-04-2019  22-04-2019  Standard Class    DP-13000

     region       product_id         category  sales  quantity  profit
45  Central  OFF-BI-10003291  Office Supplies   17.5         2     8.2
46  Central  OFF-ST-10001713  Office Supplies  212.0         4     8.5
47     East  TEC-AC-10002167       Technology   45.0         3     5.0
48     East  TEC-PH-10003988       Technology   21.8         2     6.1
49  Central  OFF-BI-10004410  Office Supplies   38.2         6    18.0

info() - Describe about data

In [ ]:
print(orders.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     50 non-null     object
 1   order_date   50 non-null     object
 2   ship_date    50 non-null     object
 3   ship_mode    50 non-null     object
 4   customer_id  50 non-null     object
 5   region       50 non-null     object
 6   product_id   50 non-null     object
 7   category     50 non-null     object
 8   sales        50 non-null     float64
 9   quantity     50 non-null     int64
 10  profit       50 non-null     float64
dtypes: float64(2), int64(1), object(8)
memory usage: 4.4+ KB
None

describe() - returns statics of numeric columns

In [ ]:
print(orders.describe())

             sales   quantity       profit
count    50.000000  50.000000    50.000000
mean    300.792000   3.920000   -20.550000
std     547.564035   1.977836   251.767027
min       2.500000   2.000000 -1665.100000
25%      20.075000   2.000000     2.500000
50%      74.650000   3.000000     8.350000
75%     249.875000   5.000000    17.650000
max    3083.400000   9.000000   240.300000

dtypes - Gives datatype of each column

In [ ]:
print(orders.dtypes)

order_id        object
order_date      object
ship_date       object
ship_mode       object
customer_id     object
region          object
product_id      object
category        object
sales          float64
quantity         int64
profit         float64
dtype: object

columns - return coulumn names

In [ ]:
print(orders.columns)

Index(['order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_id',
       'region', 'product_id', 'category', 'sales', 'quantity', 'profit'],
      dtype='object')

Changing column name - from ship_mode to shipping_mode

In [ ]:
orders.columns = ['order_id', 'order_date', 'ship_date', 'shipping_mode', 'customer_id',
       'region', 'product_id', 'category', 'sales', 'quantity', 'profit']

In [ ]:
print(orders.columns)

Index(['order_id', 'order_date', 'ship_date', 'shipping_mode', 'customer_id',
       'region', 'product_id', 'category', 'sales', 'quantity', 'profit'],
      dtype='object')

Changing column name - from shipping_mode to ship_mode using rename

In [ ]:
orders.rename(columns={"shipping_mode":"ship_mode"}, inplace=True)
print(orders.columns)

Index(['order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_id',
       'region', 'product_id', 'category', 'sales', 'quantity', 'profit'],
      dtype='object')

If the file doesn't have header and to assign header use df.columns attribute

In [ ]:
a=pd.read_csv('orders.csv',header=None)

To retrieve single column only

In [ ]:
orders.order_id.head()

0    CA-2020-152156
1    CA-2020-152156
2    CA-2020-138688
3    US-2019-108966
4    US-2019-108966
Name: order_id, dtype: object

To retrive single column we can also use square brackets

In [ ]:
orders['order_id'].head()

0    CA-2020-152156
1    CA-2020-152156
2    CA-2020-138688
3    US-2019-108966
4    US-2019-108966
Name: order_id, dtype: object

Retrieve Multiple cols

In [ ]:
new_orders=orders[['order_id','customer_id']]
new_orders.head()

         order_id customer_id
0  CA-2020-152156    CG-12520
1  CA-2020-152156    CG-12520
2  CA-2020-138688    DV-13045
3  US-2019-108966    SO-20335
4  US-2019-108966    SO-20335

Type -
*   DataFrame with Single col - Series
*   DataFrame with multiple col - DataFrame

In [ ]:
type(orders)

pandas.core.frame.DataFrame

In [ ]:
type(orders['order_id'])

pandas.core.series.Series

In [ ]:
type(orders[['order_id','customer_id']])

pandas.core.frame.DataFrame

Retrieve specific rows and specific cols

*   df.iloc[row_index]
*   df.iloc[[row_index],col_index]

In [ ]:
orders.iloc[0:3]

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Office Supplies,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Standard Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9

In [ ]:
orders.iloc[[0,1,4]]

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Office Supplies,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5

In [ ]:
orders.iloc[[0,1,4],0:3]

         order_id  order_date   ship_date
0  CA-2020-152156  08-11-2020  11-11-2020
1  CA-2020-152156  08-11-2020  11-11-2020
4  US-2019-108966  11-10-2019  18-10-2019

In [ ]:
orders.iloc[0:3,0:3]

         order_id  order_date   ship_date
0  CA-2020-152156  08-11-2020  11-11-2020
1  CA-2020-152156  08-11-2020  11-11-2020
2  CA-2020-138688  12-06-2020  16-06-2020

In [ ]:
orders.iloc[[4, 5, 8], [0,4]]

         order_id customer_id
4  US-2019-108966    SO-20335
5  CA-2018-115812    BH-11710
8  CA-2018-115812    BH-11710

**loc (Label-based):**
*   Uses the explicit names of rows and columns (e.g., df.loc['row_name', 'col_name'])
*   Includes both start and end points when slicing.

**.iloc (Integer position-based):**
*   Uses whole numbers for row and column order (e.g., df.iloc[0, 2])
*   Follows standard Python behavior by including the start index and excluding the end index when slicing.
*   Returns an error if you try to use a number that is out of bounds.

In [ ]:
orders.loc[0:3]

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Office Supplies,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Standard Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0

In [ ]:
orders.loc[0:3,'order_id']

0    CA-2020-152156
1    CA-2020-152156
2    CA-2020-138688
3    US-2019-108966
Name: order_id, dtype: object

In [ ]:
orders.loc[0:3,['order_id','customer_id']]

         order_id customer_id
0  CA-2020-152156    CG-12520
1  CA-2020-152156    CG-12520
2  CA-2020-138688    DV-13045
3  US-2019-108966    SO-20335

In [ ]:
orders.loc[[4,5,8],['order_id','customer_id']]

         order_id customer_id
4  US-2019-108966    SO-20335
5  CA-2018-115812    BH-11710
8  CA-2018-115812    BH-11710

Setting particular row as index

In [ ]:
orders.set_index('order_id').head()

,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
order_id,,,,,,,,,,
CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Office Supplies,262.0,2,41.9
CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
CA-2020-138688,12-06-2020,16-06-2020,Standard Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5

In [ ]:
orders.head()  #index not set as order_id col

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Office Supplies,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Standard Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5

In [ ]:
orders.set_index('order_id',inplace=True)

In [ ]:
orders.head()

,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
order_id,,,,,,,,,,
CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Office Supplies,262.0,2,41.9
CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
CA-2020-138688,12-06-2020,16-06-2020,Standard Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5

In [ ]:
orders.loc['CA-2020-152156']

,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
order_id,,,,,,,,,,
CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Office Supplies,262.0,2,41.9
CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6

In [ ]:
orders.loc['CA-2020-152156','order_date' : 'customer_id']

                order_date   ship_date     ship_mode customer_id
order_id
CA-2020-152156  08-11-2020  11-11-2020  Second Class    CG-12520
CA-2020-152156  08-11-2020  11-11-2020  Second Class    CG-12520

In [ ]:
orders.loc[['CA-2020-152156','CA-2020-138688'],'order_date' : 'customer_id']

                order_date   ship_date       ship_mode customer_id
order_id
CA-2020-152156  08-11-2020  11-11-2020    Second Class    CG-12520
CA-2020-152156  08-11-2020  11-11-2020    Second Class    CG-12520
CA-2020-138688  12-06-2020  16-06-2020  Standard Class    DV-13045

In [ ]:
orders.reset_index(inplace=True)

In [ ]:
orders.head()

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Office Supplies,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Standard Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5

Sorting

In [ ]:
orders.sort_index()

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Office Supplies,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Standard Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

In [ ]:
orders.sort_index(ascending=False)

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
2,CA-2020-138688,12-06-2020,16-06-2020,Standard Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Office Supplies,262.0,2,41.9

In [ ]:
orders.sort_values('quantity', ascending=False)

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
2,CA-2020-138688,12-06-2020,16-06-2020,Standard Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Office Supplies,262.0,2,41.9
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1

In [ ]:
orders.sort_values(['quantity','profit'], ascending=False)

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Office Supplies,262.0,2,41.9
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
2,CA-2020-138688,12-06-2020,16-06-2020,Standard Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1

In [ ]:
orders.sort_values(['quantity','profit'], ascending=[False, False])

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Office Supplies,262.0,2,41.9
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
2,CA-2020-138688,12-06-2020,16-06-2020,Standard Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1

In [ ]:
orders.sort_values(['quantity','profit'], ascending=False, inplace=True)

In [ ]:
orders

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Office Supplies,262.0,2,41.9
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
2,CA-2020-138688,12-06-2020,16-06-2020,Standard Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1

In [ ]:
orders.reset_index()  #it creates another new col named as index to remove that we use drop=True

,index,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
1,37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
2,35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
3,22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
4,5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
5,21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
6,27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
7,7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0
9,16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
10,31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
11,32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
12,9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
13,14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
14,36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
15,3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
16,11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
17,40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
18,41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
19,46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
20,20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
21,6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
22,24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
23,1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
24,13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
25,19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
26,29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
27,26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
28,34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
29,8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
30,12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
31,47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
32,15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
33,39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
34,38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
35,0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Office Supplies,262.0,2,41.9
36,44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
37,17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
38,43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
39,45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
40,2,CA-2020-138688,12-06-2020,16-06-2020,Standard Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
41,48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
42,25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
43,42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
44,33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
45,4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
46,18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
47,30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
48,23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
49,28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1

In [ ]:
orders.reset_index(drop=True,inplace=True) #inplace is used to permenantely reset

In [ ]:
orders

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
1,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
2,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
3,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
4,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
5,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
6,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0
9,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
10,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
11,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
12,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
13,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
14,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
15,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
16,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
17,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
18,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
19,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
21,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
22,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
23,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
24,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
25,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
26,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
27,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
28,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
29,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
30,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
31,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
32,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
33,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
34,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
35,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Office Supplies,262.0,2,41.9
36,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
37,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
38,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
39,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
40,CA-2020-138688,12-06-2020,16-06-2020,Standard Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
41,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
42,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
43,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
44,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
45,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
46,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
47,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
48,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
49,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1

Filtering

In [ ]:
orders.loc[orders['region']=='East'] #orders[orders['region']=='East'] this is also works for all cols

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
6,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
10,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
11,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
26,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
31,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
41,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
44,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
47,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
48,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
49,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1

In [ ]:
orders.loc[orders['region']=='East',['order_id','customer_id','region']]

          order_id customer_id region
6   US-2019-150630    TB-21520   East
10  US-2019-150630    TB-21520   East
11  US-2019-150630    TB-21520   East
26  US-2019-150630    TB-21520   East
31  CA-2020-169194    LH-16900   East
41  CA-2020-169194    LH-16900   East
44  US-2019-150630    TB-21520   East
47  US-2019-150630    TB-21520   East
48  US-2021-156909    SF-20065   East
49  US-2019-150630    TB-21520   East

In [ ]:
orders.loc[(orders['region']=='East') & (orders['profit']>0)]

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
10,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
26,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
31,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
41,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
44,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
47,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1

In [ ]:
orders.loc[~(orders['region']=='East'),['order_id','customer_id','region']] # ~ inverse

          order_id customer_id   region
0   CA-2018-115812    BH-11710     West
1   CA-2019-117415    SN-20710  Central
2   CA-2020-117590    GH-14485  Central
3   CA-2020-137330    KB-16585  Central
4   CA-2018-115812    BH-11710     West
5   CA-2020-137330    KB-16585  Central
7   CA-2018-115812    BH-11710     West
8   CA-2019-115742    DP-13000  Central
9   CA-2018-105893    PK-19075  Central
12  CA-2018-115812    BH-11710     West
13  US-2019-118983    HP-14815  Central
14  CA-2020-117590    GH-14485  Central
15  US-2019-108966    SO-20335    South
16  CA-2018-115812    BH-11710     West
17  CA-2019-117415    SN-20710  Central
18  CA-2021-120999    LC-16930  Central
19  CA-2018-146703    PO-18865  Central
20  CA-2018-143336    ZD-21925     West
21  CA-2018-115812    BH-11710     West
22  CA-2019-106320    EB-13870     West
23  CA-2020-152156    CG-12520    South
24  CA-2020-161389    IM-15070     West
25  CA-2018-143336    ZD-21925     West
27  CA-2020-121755    EH-13945     West
28  CA-2021-107727    MA-17560  Central
29  CA-2018-115812    BH-11710     West
30  CA-2021-114412    AA-10480    South
32  US-2019-118983    HP-14815  Central
33  CA-2019-117415    SN-20710  Central
34  CA-2019-117415    SN-20710  Central
35  CA-2020-152156    CG-12520    South
36  CA-2020-118255    ON-18715  Central
37  CA-2018-167164    AG-10270     West
38  CA-2021-139619    ES-14080    South
39  CA-2020-118255    ON-18715  Central
40  CA-2020-138688    DV-13045     West
42  CA-2020-121755    EH-13945     West
43  CA-2020-101343    RA-19885     West
45  US-2019-108966    SO-20335    South
46  CA-2018-143336    ZD-21925     West

In [ ]:
orders['country']='India' # Adding column

In [ ]:
orders.head()

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,country
0,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3,India
1,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4,India
2,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5,India
3,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7,India
4,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2,India

In [ ]:
orders['country']='USA' # Update column

In [ ]:
orders.head()

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,country
0,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3,USA
1,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4,USA
2,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5,USA
3,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7,USA
4,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2,USA

In [ ]:
orders.drop(columns = 'country',inplace=True)

In [ ]:
orders.head()

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
1,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
2,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
3,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
4,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2

In [ ]:
orders['profit_flag']=1 # added new col profit_flag with value 1

In [ ]:
orders.loc[orders['profit']<=0,'profit_flag']=0 # updated where profit is less than or equal to 0

In [ ]:
orders

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,profit_flag
0,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3,1
1,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4,1
2,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5,1
3,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7,1
4,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2,1
5,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1,1
6,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1,0
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7,1
8,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0,1
9,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3,1
10,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7,1
11,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7,0
12,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5,1
13,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9,0
14,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0,0
15,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0,0
16,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4,1
17,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8,1
18,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6,1
19,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5,1
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4,1
21,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0,1
22,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3,1
23,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6,1
24,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6,1
25,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0,1
26,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5,1
27,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8,1
28,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9,1
29,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8,1
30,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4,1
31,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0,1
32,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8,0
33,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1,0
34,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0,0
35,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Office Supplies,262.0,2,41.9,1
36,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8,1
37,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0,1
38,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6,1
39,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2,1
40,CA-2020-138688,12-06-2020,16-06-2020,Standard Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9,1
41,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1,1
42,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2,1
43,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9,1
44,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5,1
45,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5,1
46,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5,1
47,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1,1
48,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0,0
49,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1,0

Adding new col with multiple conditions:


*  Profit < 0 - loss
*  Profit between and 50 - low profit
*  Profit > 50 - high profit

In [ ]:
orders.loc[orders['profit']<0 , 'profit_loss'] = 'loss'

In [ ]:
orders.loc[(orders['profit']>0)  & (orders['profit']<50) , 'profit_loss'] = 'low profit'

In [ ]:
orders.loc[orders['profit']>50 , 'profit_loss'] = 'high profit'

In [ ]:
orders

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,profit_flag,profit_loss
0,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3,1,high profit
1,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4,1,low profit
2,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5,1,high profit
3,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7,1,low profit
4,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2,1,low profit
5,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1,1,low profit
6,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1,0,loss
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7,1,high profit
8,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0,1,low profit
9,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3,1,low profit
10,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7,1,low profit
11,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7,0,loss
12,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5,1,low profit
13,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9,0,loss
14,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0,0,loss
15,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0,0,loss
16,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4,1,high profit
17,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8,1,low profit
18,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6,1,low profit
19,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5,1,low profit
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4,1,low profit
21,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0,1,low profit
22,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3,1,high profit
23,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6,1,high profit
24,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6,1,high profit
25,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0,1,low profit
26,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5,1,low profit
27,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8,1,low profit
28,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9,1,low profit
29,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8,1,low profit
30,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4,1,low profit
31,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0,1,low profit
32,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8,0,loss
33,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1,0,loss
34,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0,0,loss
35,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Office Supplies,262.0,2,41.9,1,low profit
36,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8,1,low profit
37,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0,1,low profit
38,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6,1,low profit
39,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2,1,low profit
40,CA-2020-138688,12-06-2020,16-06-2020,Standard Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9,1,low profit
41,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1,1,low profit
42,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2,1,low profit
43,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9,1,low profit
44,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5,1,low profit
45,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5,1,low profit
46,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5,1,low profit
47,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1,1,low profit
48,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0,0,loss
49,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1,0,loss

In [ ]:
orders.drop(columns='profit_loss', inplace=True)

In [ ]:
orders.head()

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,profit_flag
0,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3,1
1,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4,1
2,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5,1
3,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7,1
4,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2,1

Apply function to column

In [ ]:
orders['category_len']=orders['category'].apply(len)

In [ ]:
orders.head()

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,profit_flag,category_len
0,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3,1,9
1,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4,1,15
2,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5,1,10
3,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7,1,15
4,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2,1,9

In [ ]:
def profit_loss(profit):
  if profit <= 0:
    return 'loss'
  elif profit>0 and profit<=50:
    return 'less profit'
  else:
    return 'high profit'
orders['profit_loss']=orders['profit'].apply(profit_loss)

In [ ]:
orders.head(10)

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,profit_flag,category_len,profit_loss
0,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3,1,9,high profit
1,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4,1,15,less profit
2,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5,1,10,high profit
3,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7,1,15,less profit
4,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2,1,9,less profit
5,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1,1,15,less profit
6,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1,0,9,loss
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7,1,10,high profit
8,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0,1,15,less profit
9,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3,1,15,less profit

In [ ]:
orders.drop(columns=['category_len',	'profit_loss'], inplace=True)

In [ ]:
orders.tail()

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,profit_flag
45,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5,1
46,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5,1
47,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1,1
48,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0,0
49,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1,0

In [ ]:
orders['category'].apply(str.upper)

0           FURNITURE
1     OFFICE SUPPLIES
2          TECHNOLOGY
3     OFFICE SUPPLIES
4           FURNITURE
5     OFFICE SUPPLIES
6           FURNITURE
7          TECHNOLOGY
8     OFFICE SUPPLIES
9     OFFICE SUPPLIES
10    OFFICE SUPPLIES
11    OFFICE SUPPLIES
12    OFFICE SUPPLIES
13    OFFICE SUPPLIES
14          FURNITURE
15          FURNITURE
16         TECHNOLOGY
17         TECHNOLOGY
18         TECHNOLOGY
19    OFFICE SUPPLIES
20    OFFICE SUPPLIES
21    OFFICE SUPPLIES
22          FURNITURE
23          FURNITURE
24    OFFICE SUPPLIES
25         TECHNOLOGY
26          FURNITURE
27         TECHNOLOGY
28    OFFICE SUPPLIES
29    OFFICE SUPPLIES
30    OFFICE SUPPLIES
31         TECHNOLOGY
32    OFFICE SUPPLIES
33          FURNITURE
34          FURNITURE
35    OFFICE SUPPLIES
36         TECHNOLOGY
37    OFFICE SUPPLIES
38    OFFICE SUPPLIES
39    OFFICE SUPPLIES
40    OFFICE SUPPLIES
41         TECHNOLOGY
42    OFFICE SUPPLIES
43    OFFICE SUPPLIES
44    OFFICE SUPPLIES
45    OFFICE SUPPLIES
46    OFFICE SUPPLIES
47    OFFICE SUPPLIES
48          FURNITURE
49    OFFICE SUPPLIES
Name: category, dtype: object

In [ ]:
orders['category'].str.upper()

0           FURNITURE
1     OFFICE SUPPLIES
2          TECHNOLOGY
3     OFFICE SUPPLIES
4           FURNITURE
5     OFFICE SUPPLIES
6           FURNITURE
7          TECHNOLOGY
8     OFFICE SUPPLIES
9     OFFICE SUPPLIES
10    OFFICE SUPPLIES
11    OFFICE SUPPLIES
12    OFFICE SUPPLIES
13    OFFICE SUPPLIES
14          FURNITURE
15          FURNITURE
16         TECHNOLOGY
17         TECHNOLOGY
18         TECHNOLOGY
19    OFFICE SUPPLIES
20    OFFICE SUPPLIES
21    OFFICE SUPPLIES
22          FURNITURE
23          FURNITURE
24    OFFICE SUPPLIES
25         TECHNOLOGY
26          FURNITURE
27         TECHNOLOGY
28    OFFICE SUPPLIES
29    OFFICE SUPPLIES
30    OFFICE SUPPLIES
31         TECHNOLOGY
32    OFFICE SUPPLIES
33          FURNITURE
34          FURNITURE
35    OFFICE SUPPLIES
36         TECHNOLOGY
37    OFFICE SUPPLIES
38    OFFICE SUPPLIES
39    OFFICE SUPPLIES
40    OFFICE SUPPLIES
41         TECHNOLOGY
42    OFFICE SUPPLIES
43    OFFICE SUPPLIES
44    OFFICE SUPPLIES
45    OFFICE SUPPLIES
46    OFFICE SUPPLIES
47    OFFICE SUPPLIES
48          FURNITURE
49    OFFICE SUPPLIES
Name: category, dtype: object

Missing values handling

In [ ]:
df=pd.read_csv('df.csv')
df.head()

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,NaN,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,NaN,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5

In [ ]:
df.isnull()

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,False,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False,False,False
36,False,False,False,False,False,False,False,False,False,False,False
37,False,False,False,False,False,False,False,False,False,False,False
38,False,False,False,False,False,False,False,False,False,False,False
39,False,False,False,False,False,False,False,False,False,False,False
40,False,False,False,False,False,False,False,False,False,False,False
41,False,False,False,False,False,False,False,False,False,False,False
42,False,False,False,False,False,False,False,False,False,False,False
43,False,False,False,False,False,False,False,False,False,False,False
44,False,False,False,False,False,False,False,False,False,False,False
45,False,False,False,False,False,False,False,False,False,False,False
46,False,False,False,False,False,False,False,False,False,False,False
47,False,False,False,False,False,False,False,False,False,False,False
48,False,False,False,False,False,False,False,False,False,False,False
49,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum() #finding missing values in which column

order_id       0
order_date     0
ship_date      0
ship_mode      1
customer_id    0
region         0
product_id     0
category       1
sales          0
quantity       0
profit         0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     50 non-null     object
 1   order_date   50 non-null     object
 2   ship_date    50 non-null     object
 3   ship_mode    49 non-null     object
 4   customer_id  50 non-null     object
 5   region       50 non-null     object
 6   product_id   50 non-null     object
 7   category     49 non-null     object
 8   sales        50 non-null     float64
 9   quantity     50 non-null     int64
 10  profit       50 non-null     float64
dtypes: float64(2), int64(1), object(8)
memory usage: 4.4+ KB

Drop column which contains missing values

In [ ]:
df.dropna()  #if it should from original dataframe add the parameter: inplace=True

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

In [ ]:
df.dropna(subset='category')

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,NaN,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

In [ ]:
df.dropna(subset=['category','ship_mode'])  # it removes row where there is missing value in the given columns

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

Fill the missing values

In [ ]:
df.fillna("Unknown")

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Unknown,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Unknown,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

df.bfill, df.ffill - Useful for text columns

In [ ]:
df.fillna(method='ffill')  #forward fill (also use df.ffill())

/tmp/ipykernel_3100/365168660.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')  #forward fill (also use df.ffill())

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,NaN,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

In [ ]:
df.bfill() # backward fill (also use df.fillna(method='bfill'))

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Standard Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

.mean(), .meadian() methods are used for numeric columns with missing values

In [ ]:
df['sales'].fillna(df['sales'].mean())

0      262.0
1      731.9
2       14.6
3      957.6
4       22.4
5       48.9
6        7.3
7      907.2
8       18.5
9      114.9
10    1706.2
11     911.4
12      15.6
13     408.0
14      68.8
15       2.5
16     665.9
17      55.5
18       8.6
19     213.5
20      22.7
21      19.5
22      60.3
23      71.4
24    1044.6
25      11.6
26      90.6
27    3083.4
28       9.6
29     124.2
30       3.3
31      86.3
32       6.9
33      15.8
34      29.5
35    1097.5
36     190.9
37     113.3
38     532.4
39     212.1
40     371.2
41     147.2
42      77.9
43      95.6
44      46.0
45      17.5
46     212.0
47      45.0
48      21.8
49      38.2
Name: sales, dtype: float64

Sometimes file contains ?, NA or missing in the file

In [ ]:
import numpy as np
df.replace('',np.nan)

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,NaN,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,NaN,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

Drop duplicates

In [ ]:
dup_data = {
    "name": ["Sumit", "Rahul", "Ankit",'sri','sri','sri'],
    "age": [25, 30, 35,30,30,30],
    "salary": [25000, 35000, 35000,30000,30000,30000],
}
df2=pd.DataFrame(dup_data)
print(df2)

    name  age  salary
0  Sumit   25   25000
1  Rahul   30   35000
2  Ankit   35   35000
3    sri   30   30000
4    sri   30   30000
5    sri   30   30000

In [ ]:
df2.drop_duplicates()  #by default it drops the last duplicate column

    name  age  salary
0  Sumit   25   25000
1  Rahul   30   35000
2  Ankit   35   35000
3    sri   30   30000

In [ ]:
df2.drop_duplicates(keep='last')

    name  age  salary
0  Sumit   25   25000
1  Rahul   30   35000
2  Ankit   35   35000
5    sri   30   30000

In [ ]:
df2.drop_duplicates(keep='first')

    name  age  salary
0  Sumit   25   25000
1  Rahul   30   35000
2  Ankit   35   35000
3    sri   30   30000

In [ ]:
df2.drop_duplicates(subset='age', keep='last')

    name  age  salary
0  Sumit   25   25000
2  Ankit   35   35000
5    sri   30   30000

In [ ]:
df2.drop_duplicates(subset=['age','salary'])

    name  age  salary
0  Sumit   25   25000
1  Rahul   30   35000
2  Ankit   35   35000
3    sri   30   30000

Date and Time in pandas

In [ ]:
orders.head()

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,profit_flag
0,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3,1
1,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4,1
2,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5,1
3,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7,1
4,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2,1

In [ ]:
orders['order_date']=pd.to_datetime(orders['order_date'],format='%d-%m-%Y')
df['order_date']=pd.to_datetime(df['order_date'],format='%d-%m-%Y')
orders['ship_date']=pd.to_datetime(orders['ship_date'],format='%d-%m-%Y')
df['ship_date']=pd.to_datetime(df['ship_date'],format='%d-%m-%Y')

In [ ]:
orders['order_date']

0    2018-06-09
1    2019-12-27
2    2020-12-08
3    2020-12-09
4    2018-06-09
5    2020-12-09
6    2019-09-17
7    2018-06-09
8    2019-04-18
9    2018-11-11
10   2019-09-17
11   2019-09-17
12   2018-06-09
13   2019-11-22
14   2020-12-08
15   2019-10-11
16   2018-06-09
17   2019-12-27
18   2021-09-10
19   2018-10-20
20   2018-08-27
21   2018-06-09
22   2019-09-25
23   2020-11-08
24   2020-12-05
25   2018-08-27
26   2019-09-17
27   2020-01-16
28   2021-10-19
29   2018-06-09
30   2021-04-15
31   2020-06-20
32   2019-11-22
33   2019-12-27
34   2019-12-27
35   2020-11-08
36   2020-03-11
37   2018-05-13
38   2021-09-19
39   2020-03-11
40   2020-06-12
41   2020-06-20
42   2020-01-16
43   2020-07-17
44   2019-09-17
45   2019-10-11
46   2018-08-27
47   2019-09-17
48   2021-07-16
49   2019-09-17
Name: order_date, dtype: datetime64[ns]

In [ ]:
df['order_date']

0    2020-11-08
1    2020-11-08
2    2020-06-12
3    2019-10-11
4    2019-10-11
5    2018-06-09
6    2018-06-09
7    2018-06-09
8    2018-06-09
9    2018-06-09
10   2018-06-09
11   2018-06-09
12   2021-04-15
13   2020-12-05
14   2019-11-22
15   2019-11-22
16   2018-11-11
17   2018-05-13
18   2018-08-27
19   2018-08-27
20   2018-08-27
21   2020-12-09
22   2020-12-09
23   2021-07-16
24   2019-09-25
25   2020-01-16
26   2020-01-16
27   2019-09-17
28   2019-09-17
29   2019-09-17
30   2019-09-17
31   2019-09-17
32   2019-09-17
33   2019-09-17
34   2021-10-19
35   2020-12-08
36   2020-12-08
37   2019-12-27
38   2019-12-27
39   2019-12-27
40   2019-12-27
41   2021-09-10
42   2020-07-17
43   2021-09-19
44   2020-03-11
45   2020-03-11
46   2018-10-20
47   2020-06-20
48   2020-06-20
49   2019-04-18
Name: order_date, dtype: datetime64[ns]

In [ ]:
orders['order_date'].dt.year

0     2018
1     2019
2     2020
3     2020
4     2018
5     2020
6     2019
7     2018
8     2019
9     2018
10    2019
11    2019
12    2018
13    2019
14    2020
15    2019
16    2018
17    2019
18    2021
19    2018
20    2018
21    2018
22    2019
23    2020
24    2020
25    2018
26    2019
27    2020
28    2021
29    2018
30    2021
31    2020
32    2019
33    2019
34    2019
35    2020
36    2020
37    2018
38    2021
39    2020
40    2020
41    2020
42    2020
43    2020
44    2019
45    2019
46    2018
47    2019
48    2021
49    2019
Name: order_date, dtype: int32

In [ ]:
orders['order_date'].dt.day

0      9
1     27
2      8
3      9
4      9
5      9
6     17
7      9
8     18
9     11
10    17
11    17
12     9
13    22
14     8
15    11
16     9
17    27
18    10
19    20
20    27
21     9
22    25
23     8
24     5
25    27
26    17
27    16
28    19
29     9
30    15
31    20
32    22
33    27
34    27
35     8
36    11
37    13
38    19
39    11
40    12
41    20
42    16
43    17
44    17
45    11
46    27
47    17
48    16
49    17
Name: order_date, dtype: int32

In [ ]:
orders['order_date'].dt.day_name()

0      Saturday
1        Friday
2       Tuesday
3     Wednesday
4      Saturday
5     Wednesday
6       Tuesday
7      Saturday
8      Thursday
9        Sunday
10      Tuesday
11      Tuesday
12     Saturday
13       Friday
14      Tuesday
15       Friday
16     Saturday
17       Friday
18       Friday
19     Saturday
20       Monday
21     Saturday
22    Wednesday
23       Sunday
24     Saturday
25       Monday
26      Tuesday
27     Thursday
28      Tuesday
29     Saturday
30     Thursday
31     Saturday
32       Friday
33       Friday
34       Friday
35       Sunday
36    Wednesday
37       Sunday
38       Sunday
39    Wednesday
40       Friday
41     Saturday
42     Thursday
43       Friday
44      Tuesday
45       Friday
46       Monday
47      Tuesday
48       Friday
49      Tuesday
Name: order_date, dtype: object

In [ ]:
orders[orders['order_date']> '2019-09-25']

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,profit_flag
1,CA-2019-117415,2019-12-27,2019-12-31,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4,1
2,CA-2020-117590,2020-12-08,2020-12-10,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5,1
3,CA-2020-137330,2020-12-09,2020-12-13,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7,1
5,CA-2020-137330,2020-12-09,2020-12-13,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1,1
13,US-2019-118983,2019-11-22,2019-11-26,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9,0
14,CA-2020-117590,2020-12-08,2020-12-10,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0,0
15,US-2019-108966,2019-10-11,2019-10-18,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0,0
17,CA-2019-117415,2019-12-27,2019-12-31,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8,1
18,CA-2021-120999,2021-09-10,2021-09-15,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6,1
23,CA-2020-152156,2020-11-08,2020-11-11,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6,1
24,CA-2020-161389,2020-12-05,2020-12-10,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6,1
27,CA-2020-121755,2020-01-16,2020-01-20,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8,1
28,CA-2021-107727,2021-10-19,2021-10-23,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9,1
30,CA-2021-114412,2021-04-15,2021-04-20,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4,1
31,CA-2020-169194,2020-06-20,2020-06-25,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0,1
32,US-2019-118983,2019-11-22,2019-11-26,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8,0
33,CA-2019-117415,2019-12-27,2019-12-31,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1,0
34,CA-2019-117415,2019-12-27,2019-12-31,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0,0
35,CA-2020-152156,2020-11-08,2020-11-11,Second Class,CG-12520,South,FUR-BO-10001798,Office Supplies,262.0,2,41.9,1
36,CA-2020-118255,2020-03-11,2020-03-13,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8,1
38,CA-2021-139619,2021-09-19,2021-09-23,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6,1
39,CA-2020-118255,2020-03-11,2020-03-13,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2,1
40,CA-2020-138688,2020-06-12,2020-06-16,Standard Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9,1
41,CA-2020-169194,2020-06-20,2020-06-25,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1,1
42,CA-2020-121755,2020-01-16,2020-01-20,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2,1
43,CA-2020-101343,2020-07-17,2020-07-22,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9,1
45,US-2019-108966,2019-10-11,2019-10-18,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5,1
48,US-2021-156909,2021-07-16,2021-07-18,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0,0

In [ ]:
df['transit_date']=(df['ship_date']-df['order_date']).dt.days
df.head()

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,transit_date
0,CA-2020-152156,2020-11-08,2020-11-11,Second Class,CG-12520,South,FUR-BO-10001798,NaN,262.0,2,41.9,3
1,CA-2020-152156,2020-11-08,2020-11-11,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6,3
2,CA-2020-138688,2020-06-12,2020-06-16,NaN,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9,4
3,US-2019-108966,2019-10-11,2019-10-18,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0,7
4,US-2019-108966,2019-10-11,2019-10-18,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5,7

Aggregation with Pandas

In [ ]:
orders.head()

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,profit_flag
0,CA-2018-115812,2018-06-09,2018-06-14,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3,1
1,CA-2019-117415,2019-12-27,2019-12-31,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4,1
2,CA-2020-117590,2020-12-08,2020-12-10,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5,1
3,CA-2020-137330,2020-12-09,2020-12-13,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7,1
4,CA-2018-115812,2018-06-09,2018-06-14,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2,1

In [ ]:
orders['category'].unique()  # returns unique values

array(['Furniture', 'Office Supplies', 'Technology'], dtype=object)

In [ ]:
orders['category'].nunique()  # returns distinct values count

3

In [ ]:
orders['sales'].sum()

np.float64(15039.6)

In [ ]:
orders['sales'].mean()

np.float64(300.79200000000003)

In [ ]:
orders['sales'].max()

3083.4

In [ ]:
orders['sales'].min()

2.5

In [ ]:
orders['sales'].count()

np.int64(50)

In [ ]:
orders.groupby('category')['sales'].sum()

category
Furniture          8703.6
Office Supplies    2484.6
Technology         3851.4
Name: sales, dtype: float64

In [ ]:
orders.groupby('region')['order_id'].count()

region
Central    17
East       10
South       6
West       17
Name: order_id, dtype: int64

In [ ]:
orders.groupby('category')['sales'].agg(['min','max','sum']) # multiple aggregation at once

                  min     max     sum
category
Furniture        48.9  3083.4  8703.6
Office Supplies   2.5   665.9  2484.6
Technology       21.8  1097.5  3851.4

In [ ]:
orders.groupby('category').agg({'sales':'sum', 'profit':'sum'})

                  sales  profit
category
Furniture        8703.6 -1684.3
Office Supplies  2484.6   257.1
Technology       3851.4   399.7

In [ ]:
orders.groupby('category').agg({'sales':'sum', 'profit':'mean'})

                  sales      profit
category
Furniture        8703.6 -153.118182
Office Supplies  2484.6    8.865517
Technology       3851.4   39.970000

In [ ]:
orders['category'].value_counts()

category
Office Supplies    29
Furniture          11
Technology         10
Name: count, dtype: int64

Pivot table to summarize the data


index becomes row names, columns become column names,
aggfunc applied on column passes on values
fill_value is for default value if anything is NAN.

In [ ]:
pd.pivot_table(
    orders,
    index='category',
    columns='region',
    values='sales',
    aggfunc='sum',
    fill_value=0
)

region           Central    East   South    West
category
Furniture          935.4  3279.0  1689.5  2799.7
Office Supplies   1227.5   121.9   395.6   739.6
Technology        1661.9    66.8     0.0  2122.7

Merging multiple datasets

In [ ]:
df_orders=pd.read_csv('orders.csv')
df_returns=pd.read_csv('returns.csv')

In [ ]:
df_orders.head()

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Office Supplies,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Standard Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5

In [ ]:
df_returns

  return_order_id return_reason
0  CA-2018-105893   bad quality
1  CA-2018-143336    wrong item
2  CA-2018-146703    wrong item
3  CA-2018-167164         other
4  CA-2019-106320   bad quality
5  CA-2019-115742         other
6  CA-2020-101343   bad quality
7  CA-2020-117590    wrong item

In [ ]:
df_returns.columns=['order_id','return_reason'] # changing the column nae from return_order_id to order_id

In [ ]:
df_orders = pd.merge(left=df_orders, right=df_returns, how='inner', on='order_id') # merge on order_id column

In [ ]:
df_orders.head()

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,return_reason
0,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3,bad quality
1,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0,other
2,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5,wrong item
3,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0,wrong item
4,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4,wrong item

In [ ]:
df_orders.groupby('return_reason')['sales'].sum()

return_reason
bad quality    1788.4
other            93.7
wrong item     1745.2
Name: sales, dtype: float64

In [ ]:
df_orders = pd.merge(left=df_orders, right=df_returns, how='left', on='order_id') # we can do right, outer, cross join

In [ ]:
df_orders=pd.read_csv('orders.csv')
df_returns=pd.read_csv('returns.csv')
df_returns

  return_order_id return_reason
0  CA-2018-105893   bad quality
1  CA-2018-143336    wrong item
2  CA-2018-146703    wrong item
3  CA-2018-167164         other
4  CA-2019-106320   bad quality
5  CA-2019-115742         other
6  CA-2020-101343   bad quality
7  CA-2020-117590    wrong item

If the merging column names are different we can use left_on and right_on attributes

In [ ]:
pd.merge(left=df_orders, right=df_returns, how='left', left_on='order_id', right_on='return_order_id')

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,return_order_id,return_reason
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Office Supplies,262.0,2,41.9,NaN,NaN
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6,NaN,NaN
2,CA-2020-138688,12-06-2020,16-06-2020,Standard Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9,NaN,NaN
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0,NaN,NaN
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5,NaN,NaN
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2,NaN,NaN
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0,NaN,NaN
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7,NaN,NaN
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8,NaN,NaN
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5,NaN,NaN
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3,NaN,NaN
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4,NaN,NaN
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4,NaN,NaN
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6,NaN,NaN
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9,NaN,NaN
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8,NaN,NaN
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3,CA-2018-105893,bad quality
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0,CA-2018-167164,other
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5,CA-2018-143336,wrong item
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0,CA-2018-143336,wrong item
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4,CA-2018-143336,wrong item
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1,NaN,NaN
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7,NaN,NaN
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0,NaN,NaN
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3,CA-2019-106320,bad quality
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2,NaN,NaN
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8,NaN,NaN
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1,NaN,NaN
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1,NaN,NaN
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5,NaN,NaN
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1,NaN,NaN
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7,NaN,NaN
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7,NaN,NaN
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5,NaN,NaN
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9,NaN,NaN
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5,CA-2020-117590,wrong item
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0,CA-2020-117590,wrong item
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4,NaN,NaN
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0,NaN,NaN
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1,NaN,NaN
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8,NaN,NaN
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6,NaN,NaN
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9,CA-2020-101343,bad quality
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6,NaN,NaN
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8,NaN,NaN
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2,NaN,NaN
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5,CA-2018-146703,wrong item
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0,NaN,NaN
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1,NaN,NaN
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0,CA-2019-115742,other

Conact- It is used to merge dataframes vertically

In [ ]:
emp1 = {"id":[1,2,3],
      "name":["Ankit","Sumit","Amit"],
      "salary":[100,200,300]}
emp2 = {"id":[4,5,6],
      "name":["Nachiket","Rahul","Vinay"],
      "salary":[400,500,600]}

df3 = pd.DataFrame(emp1)
df4 = pd.DataFrame(emp2)

In [ ]:
df3

   id   name  salary
0   1  Ankit     100
1   2  Sumit     200
2   3   Amit     300

In [ ]:
df4

   id      name  salary
0   4  Nachiket     400
1   5     Rahul     500
2   6     Vinay     600

In [ ]:
pd.concat([df3,df4])

   id      name  salary
0   1     Ankit     100
1   2     Sumit     200
2   3      Amit     300
0   4  Nachiket     400
1   5     Rahul     500
2   6     Vinay     600

In [ ]:
pd.concat([df3,df4], ignore_index= True) # gives continuous index

   id      name  salary
0   1     Ankit     100
1   2     Sumit     200
2   3      Amit     300
3   4  Nachiket     400
4   5     Rahul     500
5   6     Vinay     600

Read back the updated data into CSV file

In [ ]:
df.to_csv("full_orders.csv" , index = False)

Excel file

In [ ]:
df.to_excel("full_orders_excel.xlsx" , index = False)

Reading excel file

In [ ]:
excel=pd.read_excel("full_orders_excel.xlsx") #  we can use same method for JSON and parquet files
excel.tail()

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,transit_date
45,CA-2020-118255,2020-03-11,2020-03-13,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2,2
46,CA-2018-146703,2018-10-20,2018-10-25,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5,5
47,CA-2020-169194,2020-06-20,2020-06-25,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0,5
48,CA-2020-169194,2020-06-20,2020-06-25,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1,5
49,CA-2019-115742,2019-04-18,2019-04-22,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0,4

*   create_engine() method creates connection
*   mysql+pymysql driver
*   root - user name
*   mysql123 - password
*   127.0.0.1 - host (we can see it in installation
*   3306 - port
*   sys - database we want to connect (by default it's sys)

In [ ]:
# mysql
! pip install mysql-connector-python sqlalchemy pandas pymysql

Requirement already satisfied: mysql-connector-python in /usr/local/lib/python3.13/dist-packages (26.7.0)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.13/dist-packages (2.0.52)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: pymysql in /usr/local/lib/python3.13/dist-packages (1.2.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy) (4.16.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
# from sqlalchemy import create_engine , text
# engine = create_engine("mysql+pymysql://root:mysql123@127.0.0.1:3306/sys")
# query = "SELECT * FROM orders where order_id > 10"
# df = pd.read_sql(query, con=engine)

Write back the data to database

In [ ]:
# df.to_sql(name="orders_copy", con=engine, index=False, if_exists="append")
# df.to_sql(name="orders_copy", con=engine, index=False, if_exists="replace")
# df.to_sql(name="orders_copy", con=engine, index=False, if_exists="fail") - gives error if table already exists

If we don't want to change the table structure we can use text library

*   For update, merge, delete we can use this process

In [ ]:
# query = text("truncate table orders_copy")
# with engine.begin() as conn:
#     conn.execute(query)
#     conn.commit()

Working sqlite - default in python

In [ ]:
from sqlalchemy import create_engine , text
engine = create_engine('sqlite:///learning.db')
print("Successfully connected to the database!")

Successfully connected to the database!

In [ ]:
mock_data = {
    'employee_id':[1, 2, 3, 4],
    'name': ['Arjun', 'Priya', 'Rahul', 'Sneha'],
    'department': ['IT', 'HR', 'IT', 'Marketing'],
    'salary': [70000, 55000, 80000, 62000]
}

In [ ]:
df_input = pd.DataFrame(mock_data)
df_input.to_sql('employees', engine, index=False, if_exists='replace')
print("Table 'employees' successfully created inside the database!")

Table 'employees' successfully created inside the database!

In [ ]:
sql_query = """
SELECT name, salary
FROM employees
WHERE department = 'IT'
ORDER BY salary DESC;
"""
df_result = pd.read_sql(sql_query, engine)
df_result

    name  salary
0  Rahul   80000
1  Arjun   70000

JSON file

In [ ]:
import json
file=open('orders_ETL.json')
data=json.load(file)

In [ ]:
data

[{'order_id': 1,
  'order_date': '2024-01-10',
  'total_amount': 200.5,
  'customer': {'customer_id': 101,
   'name': 'John Doe',
   'email': 'johndoe@example.com',
   'address': '123 Main StSpringfield'},
  'products': [{'product_id': 'P01',
    'name': 'Wireless Mouse',
    'category': 'Electronics',
    'price': 25.0,
    'quantity': 2},
   {'product_id': 'P02',
    'name': 'Bluetooth Keyboard',
    'category': 'Electronics',
    'price': 45.0,
    'quantity': 1}]},
 {'order_id': 2,
  'order_date': '2024-01-12',
  'total_amount': 150.0,
  'customer': {'customer_id': 102,
   'name': 'Jane Smith',
   'email': 'janesmith@example.com',
   'address': '456 Oak StSpringfield'},
  'products': [{'product_id': 'P03',
    'name': 'Laptop Stand',
    'category': 'Electronics',
    'price': 75.0,
    'quantity': 1}]},
 {'order_id': 3,
  'order_date': '2024-01-12',
  'total_amount': 120.0,
  'customer': {'customer_id': 103,
   'name': 'Alice Johnson',
   'email': 'alicejohnson@example.com',
   'address': '789 Birch StSpringfield'},
  'products': [{'product_id': 'P04',
    'name': 'Gaming Headset',
    'category': 'Electronics',
    'price': 60.0,
    'quantity': 2}]},
 {'order_id': 4,
  'order_date': '2024-01-13',
  'total_amount': 300.5,
  'customer': {'customer_id': 101,
   'name': 'John Doe',
   'email': 'johndoe@example.com',
   'address': '123 Main StSpringfield'},
  'products': [{'product_id': 'P01',
    'name': 'Wireless Mouse',
    'category': 'Electronics',
    'price': 25.0,
    'quantity': 3},
   {'product_id': 'P02',
    'name': 'Bluetooth Keyboard',
    'category': 'Electronics',
    'price': 45.0,
    'quantity': 2}]},
 {'order_id': 5,
  'order_date': '2024-01-14',
  'total_amount': 180.0,
  'customer': {'customer_id': 104,
   'name': 'Bob Brown',
   'email': 'bobbrown@example.com',
   'address': '101 Maple StSpringfield'},
  'products': [{'product_id': 'P03',
    'name': 'Laptop Stand',
    'category': 'Electronics',
    'price': 75.0,
    'quantity': 1},
   {'product_id': 'P04',
    'name': 'Gaming Headset',
    'category': 'Electronics',
    'price': 60.0,
    'quantity': 1}]},
 {'order_id': 6,
  'order_date': '2024-01-14',
  'total_amount': 250.0,
  'customer': {'customer_id': 105,
   'name': 'Sania',
   'email': 'sania@example.com',
   'address': '102 Pine StSpringfield'},
  'products': [{'product_id': 'P01',
    'name': 'Wireless Mouse',
    'category': 'Electronics',
    'price': 25.0,
    'quantity': 2},
   {'product_id': 'P02',
    'name': 'Bluetooth Keyboard',
    'category': 'Electronics',
    'price': 45.0,
    'quantity': 2},
   {'product_id': 'P04',
    'name': 'Gaming Headset',
    'category': 'Electronics',
    'price': 60.0,
    'quantity': 1}]},
 {'order_id': 7,
  'order_date': '2024-01-16',
  'total_amount': 180.0,
  'customer': {'customer_id': 106,
   'name': 'Rohit',
   'email': 'rohit@example.com',
   'address': '103 Cedar StSpringfield'},
  'products': [{'product_id': 'P02',
    'name': 'Bluetooth Keyboard',
    'category': 'Electronics',
    'price': 45.0,
    'quantity': 2},
   {'product_id': 'P05',
    'name': 'Desk Organizer',
    'category': 'Furniture',
    'price': 30.0,
    'quantity': 1}]},
 {'order_id': 8,
  'order_date': '2024-01-16',
  'total_amount': 230.0,
  'customer': {'customer_id': 107,
   'name': 'Nina Patel',
   'email': 'ninapatel@example.com',
   'address': '104 Birch StSpringfield'},
  'products': [{'product_id': 'P01',
    'name': 'Wireless Mouse',
    'category': 'Electronics',
    'price': 25.0,
    'quantity': 3},
   {'product_id': 'P03',
    'name': 'Laptop Stand',
    'category': 'Electronics',
    'price': 75.0,
    'quantity': 1}]},
 {'order_id': 9,
  'order_date': '2024-01-17',
  'total_amount': 310.0,
  'customer': {'customer_id': 108,
   'name': 'Tom Harris',
   'email': 'tomharris@example.com',
   'address': '105 Oak StSpringfield'},
  'products': [{'product_id': 'P04',
    'name': 'Gaming Headset',
    'category': 'Electronics',
    'price': 60.0,
    'quantity': 2},
   {'product_id': 'P02',
    'name': 'Bluetooth Keyboard',
    'category': 'Electronics',
    'price': 45.0,
    'quantity': 2}]},
 {'order_id': 10,
  'order_date': '2024-01-18',
  'total_amount': 130.0,
  'customer': {'customer_id': 109,
   'name': 'Eva Lee',
   'email': 'evalee@example.com',
   'address': '106 Elm StSpringfield'},
  'products': [{'product_id': 'P05',
    'name': 'Desk Organizer',
    'category': 'Furniture',
    'price': 30.0,
    'quantity': 1},
   {'product_id': 'P03',
    'name': 'Laptop Stand',
    'category': 'Electronics',
    'price': 75.0,
    'quantity': 1}]},
 {'order_id': 11,
  'order_date': '2024-01-18',
  'total_amount': 250.0,
  'customer': {'customer_id': 101,
   'name': 'John Doe',
   'email': 'johndoe@example.com',
   'address': '123 Main StSpringfield'},
  'products': [{'product_id': 'P04',
    'name': 'Gaming Headset',
    'category': 'Electronics',
    'price': 60.0,
    'quantity': 2},
   {'product_id': 'P02',
    'name': 'Bluetooth Keyboard',
    'category': 'Electronics',
    'price': 45.0,
    'quantity': 2}]},
 {'order_id': 12,
  'order_date': '2024-01-19',
  'total_amount': 180.0,
  'customer': {'customer_id': 103,
   'name': 'Alice Johnson',
   'email': 'alicejohnson@example.com',
   'address': '789 Birch StSpringfield'},
  'products': [{'product_id': 'P01',
    'name': 'Wireless Mouse',
    'category': 'Electronics',
    'price': 25.0,
    'quantity': 2},
   {'product_id': 'P05',
    'name': 'Desk Organizer',
    'category': 'Furniture',
    'price': 30.0,
    'quantity': 1}]}]

In [ ]:
data[0]

{'order_id': 1,
 'order_date': '2024-01-10',
 'total_amount': 200.5,
 'customer': {'customer_id': 101,
  'name': 'John Doe',
  'email': 'johndoe@example.com',
  'address': '123 Main StSpringfield'},
 'products': [{'product_id': 'P01',
   'name': 'Wireless Mouse',
   'category': 'Electronics',
   'price': 25.0,
   'quantity': 2},
  {'product_id': 'P02',
   'name': 'Bluetooth Keyboard',
   'category': 'Electronics',
   'price': 45.0,
   'quantity': 1}]}

*   orders - orders_id, order_date, total_amount, customer_id, product_id, quantity
*   customers - customer_id, cust_name, email, address
*   products - product_id, prod_name, category, price

In [ ]:
order_id=[]  # order_table
order_date=[]
total_amount=[]
customer_id=[]
product_id=[]
quantity=[]
cust_id=[] # customer_table
cust_name=[]
email=[]
address=[]
prod_name=[] # product_table
category=[]
price=[]

In [ ]:
for row in data:
  cust_id.append(row['customer']['customer_id'])
  cust_name.append(row['customer']['name'])
  email.append(row['customer']['email'])
  address.append(row['customer']['address'])
  for product in row['products']:
    order_id.append(row['order_id'])
    order_date.append(row['order_date'])
    total_amount.append(row['total_amount'])
    quantity.append(product['quantity'])
    customer_id.append(row['customer']['customer_id'])
    product_id.append(product['product_id'])
    prod_name.append(product['name'])
    category.append(product['category'])
    price.append(product['price'])

In [ ]:

order_df=pd.DataFrame({
    'order_id': order_id,
    'order_date': order_date,
    'total_amount': total_amount,
    'quantity': quantity,
    'customer_id': customer_id,
    'product_id': product_id
})

In [ ]:
order_df

    order_id  order_date  total_amount  quantity  customer_id product_id
0          1  2024-01-10         200.5         2          101        P01
1          1  2024-01-10         200.5         1          101        P02
2          2  2024-01-12         150.0         1          102        P03
3          3  2024-01-12         120.0         2          103        P04
4          4  2024-01-13         300.5         3          101        P01
5          4  2024-01-13         300.5         2          101        P02
6          5  2024-01-14         180.0         1          104        P03
7          5  2024-01-14         180.0         1          104        P04
8          6  2024-01-14         250.0         2          105        P01
9          6  2024-01-14         250.0         2          105        P02
10         6  2024-01-14         250.0         1          105        P04
11         7  2024-01-16         180.0         2          106        P02
12         7  2024-01-16         180.0         1          106        P05
13         8  2024-01-16         230.0         3          107        P01
14         8  2024-01-16         230.0         1          107        P03
15         9  2024-01-17         310.0         2          108        P04
16         9  2024-01-17         310.0         2          108        P02
17        10  2024-01-18         130.0         1          109        P05
18        10  2024-01-18         130.0         1          109        P03
19        11  2024-01-18         250.0         2          101        P04
20        11  2024-01-18         250.0         2          101        P02
21        12  2024-01-19         180.0         2          103        P01
22        12  2024-01-19         180.0         1          103        P05

In [ ]:
for cust_data in data:
    cust_id.append(cust_data['customer']['customer_id'])
    cust_name.append(cust_data['customer']['name'])
    email.append(cust_data['customer']['email'])
    address.append(cust_data['customer']['address'])

In [ ]:
customer_df=pd.DataFrame({
    'customer_id': cust_id,
    'name': cust_name,
    'email':email,
    'address': address
})

In [ ]:
customer_df

,customer_id,name,email,address
0,101,John Doe,johndoe@example.com,123 Main StSpringfield
1,102,Jane Smith,janesmith@example.com,456 Oak StSpringfield
2,103,Alice Johnson,alicejohnson@example.com,789 Birch StSpringfield
3,101,John Doe,johndoe@example.com,123 Main StSpringfield
4,104,Bob Brown,bobbrown@example.com,101 Maple StSpringfield
5,105,Sania,sania@example.com,102 Pine StSpringfield
6,106,Rohit,rohit@example.com,103 Cedar StSpringfield
7,107,Nina Patel,ninapatel@example.com,104 Birch StSpringfield
8,108,Tom Harris,tomharris@example.com,105 Oak StSpringfield
9,109,Eva Lee,evalee@example.com,106 Elm StSpringfield
10,101,John Doe,johndoe@example.com,123 Main StSpringfield
11,103,Alice Johnson,alicejohnson@example.com,789 Birch StSpringfield
12,101,John Doe,johndoe@example.com,123 Main StSpringfield
13,102,Jane Smith,janesmith@example.com,456 Oak StSpringfield
14,103,Alice Johnson,alicejohnson@example.com,789 Birch StSpringfield
15,101,John Doe,johndoe@example.com,123 Main StSpringfield
16,104,Bob Brown,bobbrown@example.com,101 Maple StSpringfield
17,105,Sania,sania@example.com,102 Pine StSpringfield
18,106,Rohit,rohit@example.com,103 Cedar StSpringfield
19,107,Nina Patel,ninapatel@example.com,104 Birch StSpringfield
20,108,Tom Harris,tomharris@example.com,105 Oak StSpringfield
21,109,Eva Lee,evalee@example.com,106 Elm StSpringfield
22,101,John Doe,johndoe@example.com,123 Main StSpringfield
23,103,Alice Johnson,alicejohnson@example.com,789 Birch StSpringfield

In [ ]:
product_df=pd.DataFrame({
    'product_id': product_id,
    'name': prod_name,
    'category':category,
    'price': price
})

In [ ]:
product_df

   product_id                name     category  price
0         P01      Wireless Mouse  Electronics   25.0
1         P02  Bluetooth Keyboard  Electronics   45.0
2         P03        Laptop Stand  Electronics   75.0
3         P04      Gaming Headset  Electronics   60.0
4         P01      Wireless Mouse  Electronics   25.0
5         P02  Bluetooth Keyboard  Electronics   45.0
6         P03        Laptop Stand  Electronics   75.0
7         P04      Gaming Headset  Electronics   60.0
8         P01      Wireless Mouse  Electronics   25.0
9         P02  Bluetooth Keyboard  Electronics   45.0
10        P04      Gaming Headset  Electronics   60.0
11        P02  Bluetooth Keyboard  Electronics   45.0
12        P05      Desk Organizer    Furniture   30.0
13        P01      Wireless Mouse  Electronics   25.0
14        P03        Laptop Stand  Electronics   75.0
15        P04      Gaming Headset  Electronics   60.0
16        P02  Bluetooth Keyboard  Electronics   45.0
17        P05      Desk Organizer    Furniture   30.0
18        P03        Laptop Stand  Electronics   75.0
19        P04      Gaming Headset  Electronics   60.0
20        P02  Bluetooth Keyboard  Electronics   45.0
21        P01      Wireless Mouse  Electronics   25.0
22        P05      Desk Organizer    Furniture   30.0

In [ ]:
customer_df.drop_duplicates(subset='customer_id',keep='last',inplace=True)

In [ ]:
customer_df

,customer_id,name,email,address
13,102,Jane Smith,janesmith@example.com,456 Oak StSpringfield
16,104,Bob Brown,bobbrown@example.com,101 Maple StSpringfield
17,105,Sania,sania@example.com,102 Pine StSpringfield
18,106,Rohit,rohit@example.com,103 Cedar StSpringfield
19,107,Nina Patel,ninapatel@example.com,104 Birch StSpringfield
20,108,Tom Harris,tomharris@example.com,105 Oak StSpringfield
21,109,Eva Lee,evalee@example.com,106 Elm StSpringfield
22,101,John Doe,johndoe@example.com,123 Main StSpringfield
23,103,Alice Johnson,alicejohnson@example.com,789 Birch StSpringfield

In [ ]:
product_df.drop_duplicates(subset='product_id',keep='last',inplace=True)
product_df

   product_id                name     category  price
18        P03        Laptop Stand  Electronics   75.0
19        P04      Gaming Headset  Electronics   60.0
20        P02  Bluetooth Keyboard  Electronics   45.0
21        P01      Wireless Mouse  Electronics   25.0
22        P05      Desk Organizer    Furniture   30.0

In [ ]:
order_df.to_sql('orders', engine, index=False, if_exists='replace')
customer_df.to_sql('customers', engine, index=False, if_exists='replace')
product_df.to_sql('products', engine, index=False, if_exists='replace')

5

In [ ]:
sql_query = """
SELECT orders.order_id, products.name
FROM orders
INNER JOIN
products
ON orders.product_id=products.product_id
"""
df_result = pd.read_sql(sql_query, engine)
df_result

    order_id                name
0          1      Wireless Mouse
1          1  Bluetooth Keyboard
2          2        Laptop Stand
3          3      Gaming Headset
4          4      Wireless Mouse
5          4  Bluetooth Keyboard
6          5        Laptop Stand
7          5      Gaming Headset
8          6      Wireless Mouse
9          6  Bluetooth Keyboard
10         6      Gaming Headset
11         7  Bluetooth Keyboard
12         7      Desk Organizer
13         8      Wireless Mouse
14         8        Laptop Stand
15         9      Gaming Headset
16         9  Bluetooth Keyboard
17        10      Desk Organizer
18        10        Laptop Stand
19        11      Gaming Headset
20        11  Bluetooth Keyboard
21        12      Wireless Mouse
22        12      Desk Organizer